### ISSUE TITLE
support  relative URL

### ISSUE THREAD

**Issue by perfectstorm88** [minio/console#853]
why minio console not use  relative URL?So that minio console website will not be bound to the base URL of where it is currently deployed.

such as: ONLY `http://127.0.0.1:9000/` worked,but when I use nginx to proxy, `http://127.0.0.1:8080/myminio/`  NOT WORKED!

the `index.html` use  absolute URL, why  not use  relative URL?
```html
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MinIO Browser</title>

        <link rel="icon" type="image/png" sizes="32x32" href="/minio/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/minio/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/minio/favicon-16x16.png">

        <link rel="stylesheet" href="/minio/loader.css" type="text/css">
    </head>

```

**Comment by harshavardhana** [comment]
There are no plans to support relative URLs @perfectstorm88 sorry.

**Comment by perfectstorm88** [comment]
This is a small change, but it's easy to use。(Only change the href pah from  absolute URL  to relative URL)

It's strange why we don't support it.

**Comment by PeterFalken** [comment]
Does this also apply to built in console on the minio server?
I'm experiencing a similar issue - when running the minio server behind a proxy (Traefik)

Using sample command from MinIO download/quickstart page:
`MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server /mnt/data --console-address ":9001"`

- Traefik is configured to forward request sent to domainxxx.com/minio/ to localhost:9001
- Initial page is blank, WebConsole shows errors caused by resources using absolute paths under '/static' & '/styles'
- Previous console worked fine behind reverse proxies (both nginx & traefik)
- If relative URLs are out of the question, can there be a parameter to set the base URL?

**Comment by TomHellier** [comment]
https://github.com/minio/console/issues/396 seems to say that this issue is fixed ?

**Comment by TomHellier** [comment]
@dvaldivia, happy to try it out, testing with v0.8.1 still shows the same problem though, and it looks like master still has the slash at the start of the urls. https://github.com/minio/console/blob/master/portal-ui/public/index.html . Is this on a docker container I could test with?

**Comment by dvaldivia** [comment]
@TomHellier that's the blue print index, but you are right, for some reason the compiled index doesn't reflect the change either https://github.com/minio/console/blob/master/portal-ui/build/index.html i'll look into it

**Comment by PeterFalken** [comment]
Thanks @dvaldivia  for looking into this. @TomHellier I'm also waiting for this update - I've been using MinIO with Traefik as a reverse proxy.

**Comment by thesuperzapper** [comment]
@dvaldivia the issue is still present in `v0.10.4`, that is, we serve absolute `href` paths for all static resources (for example, `/static/css/main.e33a67ba.chunk.css`, when it should be `static/css/main.e33a67ba.chunk.css`).

There must be something causing the [./portal-ui/build/index.html](https://github.com/minio/console/blob/master/portal-ui/build/index.html) to not actually be shipped when building the Minio Console binary.

**Comment by thesuperzapper** [comment]
@dvaldivia by far the easiest way to do this (for the static resources), will be using the [HTML `<base>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).

**Comment by constantine008** [comment]
same problem

**Comment by berendiwema** [comment]
+1, we can only serve Minio from subpath as well.

**Comment by adux6991** [comment]
Same need here, appreciate if this configuration is provided

**Comment by DerKorb** [comment]
[MINIO_BROWSER_REDIRECT_URL](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#envvar.MINIO_BROWSER_REDIRECT_URL)
